# Generated by Django 4.0.4 on 2022-06-11 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benfactor', to='charities.benefactor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charti', to='charities.charity'),
        ),
    ]
